"""Alembic environment configuration — reads DATABASE_URL from env (same as app)."""
import os
from logging.config import fileConfig

from sqlalchemy import engine_from_config
from sqlalchemy import pool

from alembic import context

# Alembic Config object
config = context.config

# Logging setup
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# ── Database URL from environment (same source as app's database.py) ──────────
DATABASE_URL = os.getenv(
    "DATABASE_URL",
    "sqlite:///./video_brand_builder.db",
)
config.set_main_option("sqlalchemy.url", DATABASE_URL)

# ── Import Base and ALL models so autogenerate sees the full schema ──────────
from database import Base  # noqa: E402
from models import User, Client, Project, RenderJob, ProcessedStripeSession  # noqa: E402, F401
from models.credit import CreditBalance  # noqa: E402, F401

target_metadata = Base.metadata


# ── Render postgresql.JSON as sa.JSON for cross-DB portability ──────────────
from sqlalchemy.dialects import postgresql  # noqa: E402


def render_item(type_, obj, autogen_context):
    """Map postgresql.JSON to generic sa.JSON in autogenerated migrations
    so they work on both SQLite (dev) and PostgreSQL (prod)."""
    if type_ == "type" and isinstance(obj, postgresql.JSON):
        autogen_context.imports.add("import sqlalchemy as sa")
        return "sa.JSON()"
    return False  # default rendering


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode.

    Configures the context with just a URL, no Engine needed.

    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        render_item=render_item,
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode.

    Creates an Engine from the config URL and runs migrations.

    """
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection, target_metadata=target_metadata,
            render_item=render_item,
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()